services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "443:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /etc/letsencrypt/live/${DOMAIN}/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /etc/letsencrypt/live/${DOMAIN}/privkey.pem
    volumes:
      - /opt/letsencrypt:/etc/letsencrypt
      - registory-store:/var/lib/registry

volumes:
  registory-store:
    driver: local
    driver_opts:
      type: none
      device: /mnt/usb/registry
      o: bind
